#!/bin/bash
if [ -z "$1" ]
  then
    echo "INFO: Using random wallpaper"
    bg="$(shuf -n1 -e ~/.config/awesome/assets/wallpaper/*)"
  else
    bg=$1

fi

wal -n -i $bg

nitrogen --restore
nitrogen --set-zoom-fill $bg --head=0
pywalfox update
