#!/bin/bash
if [ -z "$1" ]; then
  echo "INFO: Using random wallpaper"
  bg="$(shuf -n1 -e ~/.config/awesome/assets/wallpaper/*)"
else
  bg=$1

fi

# Update colors
#wal -n -i $bg -b "#232136"
#wal -n -i $bg -b "#1F1F1F"
wal -n -i $bg --saturate 0.2
pywalfox update
# . ~/Sync/Projects/Youwal/youwal

nitrogen --restore
nitrogen --set-zoom-fill $bg --head=1

pywal-discord
killall picom
picom &
setxkbmap de
