#!/bin/bash
if [ -z "$1" ]; then
	echo "INFO: Using random wallpaper"
	bg="$(shuf -n1 -e ~/.config/awesome/assets/wallpaper/*)"
else
	bg=$1

fi

# Update colors
wal -n -i $bg
pywalfox update
. ~/Sync/Projects/Youwal/youwal

nitrogen --restore
nitrogen --set-zoom-fill $bg --head=0

pywal-discord
